modLoader="javafml" 
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="sci"
version="1.18.2-1.0.0"
displayName="Such Complicated Improvements[SCI]"

[[dependencies.sci]]
    modId="forge" 
    mandatory=true 
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sci]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"